version: '3.1'
services:
  api:
    build:
      context: api
    env_file:
      - api/.env
    ports:
      - '3001:3001'
  ui:
    build:
      context: ui
    env_file:
      - ui/.env
    ports:
      - '3000:80'
